from bills import Account
from bills import Sub_account

class BillsPlan:
    def __init__(self) -> None:
        self.accounts = [Account("Receitas", 
                                    [Sub_account("Dinheiro"),
                                    Sub_account("Cheque"),
                                    Sub_account("Cartão"),
                                    Sub_account("Faturado"),
                                    Sub_account("Financeiras"),
                                    Sub_account("Transferências/PIX"),
                                    Sub_account("Aportes")]),
                        
                        Account("Despesas Operacionais",
                                    [Sub_account("Aluguel"),
                                    Sub_account("Material de Expediente"),
                                    Sub_account("Energia"),
                                    Sub_account("Água"),
                                    Sub_account("Telefonia e Internet"),
                                    Sub_account("Software"),
                                    Sub_account("Contabilidade"),
                                    Sub_account("Material de Limpeza"),
                                    Sub_account("Diversos"),
                                    Sub_account("Alimentação"),
                                    Sub_account("Manutenção Predial"),
                                    Sub_account("Insumos")]),
                        
                        Account("Fornecedores e Terceiros",
                                    [Sub_account("Fornecedores"),
                                    Sub_account("Serviços de Terceiros"),
                                    Sub_account("Diferença de ICMS"),
                                    Sub_account("Frete"),
                                    Sub_account("Diversos")]),
                        
                        Account("Impostos",
                                    [Sub_account("Simples Nacional - DAS"),
                                    Sub_account("IRPJ"),
                                    Sub_account("Alvará Prefeitura"),
                                    Sub_account("IPTU")]),

                        Account("Despesas Comerciais",
                                    [Sub_account("Propaganda"),
                                    Sub_account("Comissões"),
                                    Sub_account("Alimentação"),
                                    Sub_account("Viagens")]),

                        Account("Despesas com Pessoal",
                                    [Sub_account("Salário"),
                                    Sub_account("INSS"),
                                    Sub_account("FGTS"),
                                    Sub_account("Vale Transporte"),
                                    Sub_account("13 Salário"),
                                    Sub_account("Férias"),
                                    Sub_account("Recisão"),
                                    Sub_account("Multa FGTS"),
                                    Sub_account("Vale Salário"),
                                    Sub_account("Vale Alimentação"),
                                    Sub_account("Hora Extra"),
                                    Sub_account("Uniforme"),
                                    Sub_account("Bonificação"),
                                    Sub_account("ASO"),
                                    Sub_account("EPI's")]),

                        Account("Despesas Financeiras",
                                    [Sub_account("Juros"),
                                    Sub_account("Tarifas Bancárias"),
                                    Sub_account("Diversos")]),

                        Account("Despesas com Imobilizado",
                                    [Sub_account("Moveis"),
                                    Sub_account("Maq, Equip e Ferramentas"),
                                    Sub_account("Veículos"),
                                    Sub_account("Computadores e Afins")]),

                        Account("Despesas com Veículos",
                                    [Sub_account("Combustivel"),
                                    Sub_account("Serviços"),
                                    Sub_account("Pneus"),
                                    Sub_account("Peças"),
                                    Sub_account("Emplacamento"),
                                    Sub_account("Seguro"),
                                    Sub_account("Infrações")]),
                        
                        Account("Emprestimos",
                                    [Sub_account("Pronampe Itau"),
                                    Sub_account("Pronampe Banco do Brasil")])
                        ]