from Bills import Account

class BillsPlan:
    def __init__(self) -> None:
        accounts = [Account("Receitas")]
        accounts[0].AddSub_account("Dinheiro")
        accounts[0].AddSub_account("Cheque")
        accounts[0].AddSub_account("Cartão")
        accounts[0].AddSub_account("Faturado")
        accounts[0].AddSub_account("Financeiras")
        accounts[0].AddSub_account("Transferências")
        accounts[0].AddSub_account("Aportes")
        
        accounts.append(Account("Despesas Operacionais"))
        accounts[1].AddSub_account("Aluguel")
        accounts[1].AddSub_account("Material de Expediente")
        accounts[1].AddSub_account("Energia")
        accounts[1].AddSub_account("Água")
        accounts[1].AddSub_account("Telefonia e Internet")
        accounts[1].AddSub_account("Software")
        accounts[1].AddSub_account("Contabilidade")
        accounts[1].AddSub_account("Material de Limpeza")
        accounts[1].AddSub_account("Diversos")
        accounts[1].AddSub_account("Alimentação")
        accounts[1].AddSub_account("Manutenção Predial")
        accounts[1].AddSub_account("Insumos")
        
        accounts.append(Account("Fornecedores e Terceiros"))
        accounts[2].AddSub_account("Fornecedores")
        accounts[2].AddSub_account("Serviços de Terceiros")
        accounts[2].AddSub_account("Diferença de ICMS")
        accounts[2].AddSub_account("Frete")
        accounts[2].AddSub_account("Diversos")
        
        accounts.append(Account("Impostos"))
        accounts[3].AddSub_account("Simples Nacional - DAS")
        accounts[3].AddSub_account("IRPJ")
        accounts[3].AddSub_account("Alvará Prefeitura")
        accounts[3].AddSub_account("IPTU")
        
        accounts.append(Account("Despesas Comerciais"))
        accounts[4].AddSub_account("Propaganda")
        accounts[4].AddSub_account("Comissões")
        accounts[4].AddSub_account("Alimentação")
        accounts[4].AddSub_account("Viagens")
        
        accounts.append(Account("Despesas com Pessoal"))
        accounts[5].AddSub_account("Salário")
        accounts[5].AddSub_account("INSS")
        accounts[5].AddSub_account("FGTS")
        accounts[5].AddSub_account("Vale Transporte")
        accounts[5].AddSub_account("13 Salário")
        accounts[5].AddSub_account("Férias")
        accounts[5].AddSub_account("Recisão")
        accounts[5].AddSub_account("Multa FGTS")
        accounts[5].AddSub_account("Vale Salário")
        accounts[5].AddSub_account("Vale Alimentação")
        accounts[5].AddSub_account("Hora Extra")
        accounts[5].AddSub_account("Uniforme")
        accounts[5].AddSub_account("Bonificação")
        accounts[5].AddSub_account("ASO")
        accounts[5].AddSub_account("EPI's")
        
        accounts.append(Account("Despesas Financeiras"))
        accounts[6].AddSub_account("Juros")
        accounts[6].AddSub_account("Tarifas Bancárias")
        accounts[6].AddSub_account("Diversos")
        
        accounts.append(Account("Despesas com Imobilizado"))
        accounts[7].AddSub_account("Moveis")
        accounts[7].AddSub_account("Maq, Equip e Ferramentas")
        accounts[7].AddSub_account("Veículos")
        accounts[7].AddSub_account("Computadores e Afins")
        
        accounts.append(Account("Despesas com Veículos"))
        accounts[8].AddSub_account("Combustivel")
        accounts[8].AddSub_account("Serviços")
        accounts[8].AddSub_account("Pneus")
        accounts[8].AddSub_account("Peças")
        accounts[8].AddSub_account("Emplacamento")
        accounts[8].AddSub_account("Seguro")
        accounts[8].AddSub_account("Infrações")
        